CREATE DATABASE IF NOT EXISTS juejin
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'huangnv'@'%' IDENTIFIED BY '11447';
GRANT ALL PRIVILEGES ON juejin.* TO 'huangnv'@'%';
FLUSH PRIVILEGES;
